# For the hostnames to work an entry in /etc/hosts is needed:
# 127.0.0.1 authentik.orthos2.test orthos2.orthos2.test cobbler.orthos2.test netbox.orthos2.test
include:
  - docker/authentik/compose.authentik.yaml
  - docker/netbox/compose.netbox.yml

services:
  proxy:
    image: traefik:v3.6
    container_name: traefik
    command:
      - --accesslog=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
      - ./docker/traefik/certs/authentik.orthos2.test.crt:/certs/authentik.orthos2.test.crt:ro,z
      - ./docker/traefik/certs/authentik.orthos2.test.key:/certs/authentik.orthos2.test.key:ro,z
      - ./docker/traefik//dynamic_conf.yaml:/etc/traefik/dynamic/certs.yaml:ro,z
    restart: always
    networks:
      orthos:
        aliases:
          - authentik.orthos2.test
    security_opt:
      - label:disable
  orthos2:
    build:
      context: .
      dockerfile: docker/develop-tw.dockerfile
    hostname: orthos2.orthos2.test
    env_file:
      - "docker/orthos/orthos2.env"
    cap_add:
      - NET_RAW
    volumes:
      - ./:/code:z
    networks:
      - orthos
    depends_on:
      orthos2_database:
        condition: service_healthy
      netbox:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthos2-http.rule=Host(`orthos2.orthos2.test`)"
      - "traefik.http.routers.orthos2-http.entrypoints=web"
      - "traefik.http.routers.orthos2-http.middlewares=orthos2-https"
      - "traefik.http.middlewares.orthos2-https.redirectScheme.scheme=https"
      - "traefik.http.routers.orthos2-https.rule=Host(`orthos2.orthos2.test`)"
      - "traefik.http.routers.orthos2-https.entrypoints=websecure"
      - "traefik.http.routers.orthos2-https.tls=true"
      - "traefik.http.services.orthos2.loadbalancer.server.port=8000"
  orthos2_taskmanager:
    build:
      context: .
      dockerfile: docker/develop-tw.dockerfile
    environment:
      ORTHOS2_MODE: "taskmanager"
    env_file:
      - "docker/orthos/orthos2.env"
    cap_add:
      - NET_RAW
    volumes:
      - ./:/code
    networks:
      - orthos
    depends_on:
      orthos2_database:
        condition: service_healthy
      orthos2:
        condition: service_healthy
  orthos2_database:
    image: postgres
    restart: always
    hostname: database.orthos2.test
    env_file:
      - "docker/orthos/db.env"
    networks:
      - orthos
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -d $${POSTGRES_USER} -U $${POSTGRES_USER}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
  cobbler:
    hostname: cobbler.orthos2.test
    build:
      context: docker/cobbler
      dockerfile: cobbler.dockerfile
    networks:
      - orthos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cobbler-http.rule=Host(`cobbler.orthos2.test`)"
      - "traefik.http.routers.cobbler-http.entrypoints=web"
      - "traefik.http.routers.cobbler-https.rule=Host(`cobbler.orthos2.test`)"
      - "traefik.http.routers.cobbler-https.entrypoints=websecure"
      - "traefik.http.routers.cobbler-https.tls=true"
      - "traefik.http.services.cobbler.loadbalancer.server.port=80"
  serial_console:
    hostname: sconsole.orthos2.test
    networks:
      - orthos
    build:
      context: docker/serial-console
      dockerfile: serial-console.dockerfile
    #ports:
    #  - 22:22
  machine_bmc:
    hostname: bmc.orthos2.test
    networks:
      - orthos
    build:
      context: docker/bmc
      dockerfile: bmc.dockerfile
    ports:
      - "9001:9001"


volumes:
  database:
    driver: local
networks:
  orthos:
