services:
  proxy:
    image: traefik:v3.6
    container_name: traefik
    command:
      - --accesslog=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    restart: always
    security_opt:
      - label:disable
  orthos2:
    image: registry.opensuse.org/systemsmanagement/orthos2/containers/orthos2:1.13
    secrets:
      - NetboxToken
      - OrthosKey
      - OIDCsecret
    env_file:
      - ".env"
    cap_add:
      - NET_RAW
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthos2-http.rule=Host(`${FQDN:?error}`)"
      - "traefik.http.routers.orthos2-http.entrypoints=web"
      - "traefik.http.routers.orthos2-http.middlewares=orthos2-https"
      - "traefik.http.middlewares.orthos2-https.redirectScheme.scheme=https"
      - "traefik.http.routers.orthos2-https.rule=Host(`${FQDN:?error}`)"
      - "traefik.http.routers.orthos2-https.entrypoints=websecure"
      - "traefik.http.routers.orthos2-https.tls=true"
      - "traefik.http.services.orthos2.loadbalancer.server.port=8000"
  orthos2_taskmanager:
    image: registry.opensuse.org/systemsmanagement/orthos2/containers/orthos2:1.13
    secrets:
      - NetboxToken
      - OrthosKey
      - OIDCsecret
    environment:
      ORTHOS2_MODE: "taskmanager"
    env_file:
      - ".env"
    cap_add:
      - NET_RAW
    depends_on:
      orthos2:
        condition: service_healthy

secrets:
  NetboxToken:
    file: docker/secrets/NetboxToken
  OrthosKey:
    file: docker/secrets/OrthosKey
  OIDCsecret:
    file: docker/secrets/OIDCsecret
volumes:
  database:
    driver: local
