services:
  netbox:
    hostname: netbox.orthos2.test
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbox-http.rule=Host(`netbox.orthos2.test`)"
      - "traefik.http.routers.netbox-http.entrypoints=web"
      - "traefik.http.routers.netbox-https.rule=Host(`netbox.orthos2.test`)"
      - "traefik.http.routers.netbox-https.entrypoints=websecure"
      - "traefik.http.routers.netbox-https.tls=true"
      - "traefik.http.services.netbox.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.netbox-static-fix.replacepathregex.regex=^/(.*)/static/"
      - "traefik.http.middlewares.netbox-static-fix.replacepathregex.replacement=/static/"
      - "traefik.http.routers.netbox-https.middlewares=netbox-static-fix"
