[flake8]
max-line-length = 120
exclude = 
    orthos2/data/migrations/*,
    orthos2/taskmanager/migrations/*,
per-file-ignores =
    orthos2/meta/data/ansible/inventory_plugins/orthos2.py:E402
    orthos2/meta/data/ansible/callback_plugins/orthos2_history.py:E402
