from orthos2.api.commands.add import (
    AddAnnotationCommandGet,
    AddAnnotationCommandPost,
    AddArchitectureCommand,
    AddBMCCommandGet,
    AddBMCCommandPost,
    AddCommand,
    AddDeviceTypeCommand,
    AddMachineCommand,
    AddManufacturerCommand,
    AddRemotePowerCommandGet,
    AddRemotePowerCommandPost,
    AddRemotePowerDeviceCommand,
    AddSerialConsoleCommandGet,
    AddSerialConsoleCommandPost,
    AddSerialConsoleTypeCommand,
    AddServerConfigCommand,
    AddSingleTaskCommand,
    AddSystemCommand,
    AddVMCommandGet,
    AddVMCommandPost,
)
from orthos2.api.commands.delete import (
    DeleteArchitectureCommand,
    DeleteCommand,
    DeleteDeviceTypeCommand,
    DeleteMachineCommand,
    DeleteManufacturerCommand,
    DeleteNetworkInterfaceCommand,
    DeleteRemotePowerCommand,
    DeleteRemotePowerDeviceCommand,
    DeleteSerialConsoleCommand,
    DeleteSerialConsoleTypeCommand,
    DeleteServerConfigCommand,
    DeleteSingleTaskCommand,
    DeleteSystemCommand,
)
from orthos2.api.commands.edit import (
    EditArchitectureCommand,
    EditCommand,
    EditDeviceTypeCommand,
    EditManufacturerCommand,
    EditSerialConsoleTypeCommand,
    EditServerConfigCommand,
    EditSingleTaskCommand,
    EditSystemCommand,
)
from orthos2.api.commands.info import (
    ArchitectureInfoCommand,
    DeviceTypeInfoCommand,
    EnclosureInfoCommand,
    InfoCommand,
    ManufacturerInfoCommand,
    RemotePowerDeviceInfoCommand,
    SerialConsoleTypeInfoCommand,
    SingleTaskInfoCommand,
    SystemInfoCommand,
)
from orthos2.api.commands.power import PowerCommand
from orthos2.api.commands.query import QueryCommand
from orthos2.api.commands.regenerate import RegenerateCommand
from orthos2.api.commands.release import ReleaseCommand
from orthos2.api.commands.rescan import RescanCommand
from orthos2.api.commands.reservationhistory import ReservationHistoryCommand
from orthos2.api.commands.reserve import ReserveCommandGet, ReserveCommandPost
from orthos2.api.commands.serverconfig import ServerConfigCommand
from orthos2.api.commands.setup import SetupCommand

__all__ = [
    "EnclosureInfoCommand",
    "RemotePowerDeviceInfoCommand",
    "ManufacturerInfoCommand",
    "DeviceTypeInfoCommand",
    "SerialConsoleTypeInfoCommand",
    "SingleTaskInfoCommand",
    "SystemInfoCommand",
    "ArchitectureInfoCommand",
    "InfoCommand",
    "QueryCommand",
    "ReserveCommandGet",
    "ReserveCommandPost",
    "ReleaseCommand",
    "ReservationHistoryCommand",
    "RescanCommand",
    "RegenerateCommand",
    "ServerConfigCommand",
    "SetupCommand",
    "PowerCommand",
    "AddCommand",
    "AddVMCommandGet",
    "AddVMCommandPost",
    "AddMachineCommand",
    "AddSerialConsoleCommandGet",
    "AddSerialConsoleCommandPost",
    "AddAnnotationCommandGet",
    "AddAnnotationCommandPost",
    "AddRemotePowerCommandPost",
    "AddRemotePowerCommandGet",
    "DeleteCommand",
    "DeleteMachineCommand",
    "DeleteSerialConsoleCommand",
    "DeleteRemotePowerCommand",
    "DeleteRemotePowerDeviceCommand",
    "DeleteNetworkInterfaceCommand",
    "AddBMCCommandPost",
    "AddBMCCommandGet",
    "AddRemotePowerDeviceCommand",
    "AddManufacturerCommand",
    "DeleteManufacturerCommand",
    "EditCommand",
    "EditManufacturerCommand",
    "AddDeviceTypeCommand",
    "DeleteDeviceTypeCommand",
    "EditDeviceTypeCommand",
    "AddSerialConsoleTypeCommand",
    "DeleteSerialConsoleTypeCommand",
    "EditSerialConsoleTypeCommand",
    "AddSystemCommand",
    "DeleteSystemCommand",
    "EditSystemCommand",
    "AddSingleTaskCommand",
    "DeleteSingleTaskCommand",
    "EditSingleTaskCommand",
    "AddArchitectureCommand",
    "DeleteArchitectureCommand",
    "EditArchitectureCommand",
    "AddServerConfigCommand",
    "DeleteServerConfigCommand",
    "EditServerConfigCommand",
]
