# Generated by Django 3.1.4 on 2021-03-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePowerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switching_device', models.CharField(choices=[('rpower_device', 'Remotepower Device (e. g. Raritan)'), ('bmc', 'BMC'), ('hypervisor', 'Hypervisor (physical host)')], max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('use_key', models.BooleanField(verbose_name='Use SSH Key')),
                ('use_port', models.BooleanField(verbose_name='Use Port')),
                ('fence', models.CharField(choices=[('virsh', 'virsh'), ('ipmitool', 'ipmitool'), ('raritan', 'raritan')], max_length=255, verbose_name='Fencing Agent')),
            ],
        ),
        migrations.DeleteModel(
            name='DominionPX',
        ),
        migrations.DeleteModel(
            name='ILO',
        ),
        migrations.DeleteModel(
            name='IPMI',
        ),
        migrations.DeleteModel(
            name='LibvirtLXC',
        ),
        migrations.DeleteModel(
            name='LibvirtQEMU',
        ),
        migrations.DeleteModel(
            name='S390',
        ),
        migrations.DeleteModel(
            name='Sentry',
        ),
        migrations.DeleteModel(
            name='Telnet',
        ),
        migrations.DeleteModel(
            name='WEBCurl',
        ),
        migrations.RemoveField(
            model_name='remotepower',
            name='device',
        ),
        migrations.RemoveField(
            model_name='remotepower',
            name='type',
        ),
        migrations.AddField(
            model_name='machine',
            name='hypervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hypervising', to='data.machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='use_bmc',
            field=models.BooleanField(default=True, verbose_name='Use BMC for powerswitching'),
        ),
        migrations.AddField(
            model_name='remotepower',
            name='hypervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.machine'),
        ),
        migrations.AlterField(
            model_name='remotepower',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remotepower',
            name='kind',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.remotepowertype', verbose_name='Powerswitch Type'),
            preserve_default=False,
        ),
    ]
