# Generated by Django 2.2.11 on 2020-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200415_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='default_profile',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Default profile'),
        ),
    ]
