# Generated by Django 3.1.4 on 2021-05-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_auto_20210505_1650"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remotepower",
            name="hypervisor",
        ),
        migrations.RemoveField(
            model_name="remotepower",
            name="management_bmc",
        ),
    ]
