# Generated by Django 3.1.4 on 2021-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_auto_20210522_1123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainadmin",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
    ]
