# Generated by Django 3.1.4 on 2021-06-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20210531_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialconsole',
            name='cscreen_server',
        ),
        migrations.AddField(
            model_name='domain',
            name='cscreen_server',
            field=models.ForeignKey(blank=True, limit_choices_to={'administrative': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data.machine', verbose_name='CScreen server'),
        ),
    ]
