# Generated by Django 3.1.4 on 2021-06-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_auto_20210624_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotepower",
            name="machine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="data.machine"
            ),
        ),
        migrations.AddField(
            model_name="remotepower",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="remotepowerdevice",
            name="fence_name",
            field=models.CharField(
                choices=[("raritan", "raritan"), ("cdu", "cdu"), ("apc", "apc")],
                max_length=255,
                verbose_name="Fence Agent",
            ),
        ),
    ]
