# Generated by Django 3.1.4 on 2021-07-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20210713_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='created',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated',
        ),
    ]
