# Generated by Django 3.1.4 on 2021-07-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_auto_20210713_0538"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="created",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="enclosure",
            name="created",
        ),
        migrations.RemoveField(
            model_name="enclosure",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="machinegroup",
            name="created",
        ),
        migrations.RemoveField(
            model_name="machinegroup",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="remotepower",
            name="created",
        ),
        migrations.RemoveField(
            model_name="remotepower",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="serialconsole",
            name="created",
        ),
        migrations.RemoveField(
            model_name="serialconsole",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="serialconsoletype",
            name="created",
        ),
        migrations.RemoveField(
            model_name="serialconsoletype",
            name="updated",
        ),
    ]
