# Generated by Django 3.1.4 on 2021-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0026_auto_20210713_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serialconsole",
            name="kernel_device",
            field=models.CharField(
                choices=[(0, "ttyS"), (1, "ttyUSB"), (2, "ttyAMA"), (3, "tty")],
                default="ttyS",
                help_text="The kernel device string as passed via kernel command line, e.g. ttyS, ttyAMA, ttyUSB,...",
                max_length=64,
                verbose_name="Kernel Device",
            ),
        ),
    ]
