# Generated by Django 3.1.4 on 2021-09-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0029_auto_20210916_1225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serialconsole",
            name="kernel_device",
            field=models.CharField(
                choices=[
                    ("ttyS", "ttyS"),
                    ("ttyUSB", "ttyUSB"),
                    ("ttyAMA", "ttyAMA"),
                    ("tty", "tty"),
                    ("None", "None"),
                ],
                default="ttyS",
                help_text="The kernel device string as passed via kernel command line, e.g. ttyS, ttyAMA, ttyUSB,...",
                max_length=64,
                verbose_name="Kernel Device",
            ),
        ),
    ]
