# Generated by Django 3.1.4 on 2021-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20210916_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialconsole',
            name='kernel_device',
            field=models.CharField(choices=[('ttyS', 'ttyS'), ('ttyUSB', 'ttyUSB'), ('ttyAMA', 'ttyAMA'), ('tty', 'tty'), ('None', 'None')], default='ttyS', help_text='The kernel device string as passed via kernel command line, e.g. ttyS, ttyAMA, ttyUSB,... "None" will remove console= kernel paramter', max_length=64, verbose_name='Kernel Device'),
        ),
    ]
