# Generated by Django 3.2.8 on 2021-11-03 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_domain_cobbler_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialconsole',
            name='rendered_command',
            field=models.CharField(blank=True, help_text='Final command which is constructed using above info and synced to cscreen server /etc/cscreenrc config', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bmc',
            name='fqdn',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='bmc',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cobbler_server',
            field=models.ManyToManyField(blank=True, limit_choices_to={'administrative': True}, related_name='cobbler_server_for', to='data.Machine', verbose_name='Cobbler server'),
        ),
        migrations.AlterField(
            model_name='remotepower',
            name='fence_name',
            field=models.CharField(choices=[('virsh', 'virsh'), ('pvm', 'pvm'), ('lpar', 'lpar'), ('fence_zvm_suse', 'fence_zvm_suse')], max_length=255, verbose_name='Fence Agent'),
        ),
        migrations.AlterField(
            model_name='serialconsole',
            name='command',
            field=models.CharField(blank=True, help_text="Use this with the 'command' type. Template matching applies.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serialconsole',
            name='kernel_device_num',
            field=models.PositiveSmallIntegerField(default=0, help_text='The kernel device number is concatenated to the kernel device string (see above).\nA value of 1 might end up in console=ttyS1 kernel command line paramter.', validators=[django.core.validators.MaxValueValidator(1024)], verbose_name='Kernel Device number'),
        ),
        migrations.AlterField(
            model_name='serialconsoletype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
