# Generated by Django 3.2.8 on 2021-11-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0035_auto_20211103_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serialconsole",
            name="kernel_device",
            field=models.CharField(
                choices=[
                    ("ttyS", "ttyS"),
                    ("ttyUSB", "ttyUSB"),
                    ("ttyAMA", "ttyAMA"),
                    ("hvc", "hvc"),
                    ("None", "None"),
                ],
                default="ttyS",
                help_text='The kernel device string as passed via kernel command line, e.g. ttyS, ttyAMA, ttyUSB,... "None" will remove console= kernel paramter',
                max_length=64,
                verbose_name="Kernel Device",
            ),
        ),
    ]
