# Generated by Django 4.2.20 on 2025-04-02 10:45

import datetime
import socket
from typing import List, NamedTuple, Optional

import django.core.validators
import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

import orthos2.data.validators


class DNSLookupTuple(NamedTuple):
    """
    Describes a DNS lookup done by the application.
    """

    ipv4: List[str]
    ipv6: List[str]


def get_ip(fqdn: str, ip_version: int = 4) -> Optional[DNSLookupTuple]:
    """
    Return all IP addresses for FQDN.

    Use `ip_version` to specify which IP version gets returned.

    IP versions (`ip_version`):
        4  - ['192.168.0.1', ...]
        6  - ['0:0:0:0:0:ffff:c0a8:1', ...]
        10 - (['192.168.0.1', ...], [0:0:0:0:0:ffff:c0a8:1, ...])
    """
    ipv4: List[str] = []
    ipv6: List[str] = []

    try:
        result = socket.getaddrinfo(fqdn, None, 0, socket.SOCK_STREAM, socket.SOL_TCP)

        for address_family in result:
            if address_family[0] == socket.AF_INET:
                ipv4.append(address_family[4][0])  # type: ignore
            elif address_family[0] == socket.AF_INET6:
                ipv6.append(address_family[4][0])  # type: ignore
    except (IndexError, socket.gaierror):
        return None

    if not ipv4:
        return None

    if ip_version == 4:
        return DNSLookupTuple(ipv4, [])
    elif ip_version == 6:
        return DNSLookupTuple([], ipv6)
    elif ip_version == 10:
        return DNSLookupTuple(ipv4, ipv6)
    else:
        raise ValueError("Unknown IP version '{}'!".format(ip_version))


def get_ipv4(fqdn: str) -> Optional[str]:
    """Return (first) IPv4 address for FQDN."""
    lookup_result = get_ip(fqdn, ip_version=4)
    if lookup_result and lookup_result.ipv4:
        return lookup_result.ipv4[0]
    return None


def get_ipv6(fqdn: str) -> Optional[str]:
    """Return (first) IPv6 address for FQDN."""
    lookup_result = get_ip(fqdn, ip_version=6)
    if lookup_result and lookup_result.ipv6:
        return lookup_result.ipv6[0]
    return None


def set_ipv4_machine_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Machine = apps.get_model("data", "Machine")
    for machine in Machine.objects.all().iterator():
        machine.ip_address_v4 = get_ipv4(machine.fqdn)
        machine.save()


def set_ipv6_machine_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Machine = apps.get_model("data", "Machine")
    for machine in Machine.objects.all().iterator():
        machine.ip_address_v6 = get_ipv6(machine.fqdn)
        machine.save()


def set_ipv4_bmc_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    BMC = apps.get_model("data", "BMC")
    for bmc in BMC.objects.all().iterator():
        bmc.ip_address_v4 = get_ipv4(bmc.fqdn)
        bmc.save()


def set_ipv6_bmc_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    BMC = apps.get_model("data", "BMC")
    for bmc in BMC.objects.all().iterator():
        bmc.ip_address_v6 = get_ipv6(bmc.fqdn)
        bmc.save()


# TODO: Rename migration before PR is finished to new Orthos 2 version
class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_domain_cobbler_server_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPRangeV4",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.GenericIPAddressField(protocol="IPv4")),
                ("end", models.GenericIPAddressField(protocol="IPv4")),
            ],
        ),
        migrations.CreateModel(
            name="IPRangeV6",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.GenericIPAddressField(protocol="IPv6")),
                ("end", models.GenericIPAddressField(protocol="IPv6")),
            ],
        ),
        migrations.AddField(
            model_name="machine",
            name="ip_address_v4",
            field=models.GenericIPAddressField(
                protocol="IPv4", unique=True, blank=True, null=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machine",
            name="ip_address_v6",
            field=models.GenericIPAddressField(
                protocol="IPv6", unique=True, blank=True, null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_ipv4_machine_defaults),
        migrations.RunPython(set_ipv6_machine_defaults),
        migrations.AddField(
            model_name="bmc",
            name="ip_address_v4",
            field=models.GenericIPAddressField(
                protocol="IPv4", unique=True, blank=True, null=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bmc",
            name="ip_address_v6",
            field=models.GenericIPAddressField(
                protocol="IPv6", unique=True, blank=True, null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_ipv4_bmc_defaults),
        migrations.RunPython(set_ipv6_bmc_defaults),
        migrations.AlterField(
            model_name="machine",
            name="last_check",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2016, 1, 1, 10, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Checked at",
            ),
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="unknown",
                        max_length=256,
                        validators=[orthos2.data.validators.DomainNameValidator()],
                    ),
                ),
                ("ip_v4", models.GenericIPAddressField(protocol="IPv4")),
                ("ip_v6", models.GenericIPAddressField(protocol="IPv6")),
                (
                    "subnet_mask_v4",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "subnet_mask_v6",
                    models.PositiveIntegerField(
                        default=64,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(127),
                        ],
                    ),
                ),
                ("enable_v4", models.BooleanField(default=True)),
                ("enable_v6", models.BooleanField(default=True)),
                (
                    "dynamic_range_v4",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="data.iprangev4"
                    ),
                ),
                (
                    "dynamic_range_v6",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="data.iprangev6"
                    ),
                ),
            ],
            options={
                "verbose_name": "Network",
                "ordering": ("-name",),
            },
        ),
    ]
