# Generated by Django 4.2.20 on 2025-04-03 13:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_domain_cobbler_server_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="last_check",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2016, 1, 1, 10, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Checked at",
            ),
        ),
    ]
