# Generated by Django 4.2.20 on 2025-05-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0044_initial_required_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="cscreen_server",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"administrative": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cscreen_server_for",
                to="data.machine",
                verbose_name="CScreen server",
            ),
        ),
    ]
