# Generated by Django 4.2.20 on 2025-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0045_alter_domain_cscreen_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="enclosure",
            name="location_rack",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AddField(
            model_name="enclosure",
            name="location_rack_position",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AddField(
            model_name="enclosure",
            name="location_room",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AddField(
            model_name="enclosure",
            name="location_site",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AddField(
            model_name="enclosure",
            name="netbox_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The ID that NetBox gives to the object.",
                verbose_name="NetBox ID",
            ),
        ),
    ]
