# Generated by Django 4.2.20 on 2025-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0046_enclosure_location_rack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="netbox_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The ID that NetBox gives to the object.",
                verbose_name="NetBox ID",
            ),
        ),
    ]
