# Generated by Django 4.2.20 on 2025-06-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0048_reintroduce_remotepowertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetboxOrthosComparisionRun",
            fields=[
                (
                    "run_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("compare_timestamp", models.DateTimeField()),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("bmc", "BMC"),
                            ("enclosure", "Enclosure"),
                            ("machine", "Machine"),
                            ("network_interface", "Network Interface"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "object_bmc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netboxorthoscomparisionruns",
                        to="data.bmc",
                    ),
                ),
                (
                    "object_enclosure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netboxorthoscomparisionruns",
                        to="data.enclosure",
                    ),
                ),
                (
                    "object_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netboxorthoscomparisionruns",
                        to="data.machine",
                    ),
                ),
                (
                    "object_network_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netboxorthoscomparisionruns",
                        to="data.networkinterface",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetboxOrthosComparisionResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=255)),
                ("orthos_result", models.CharField(max_length=255)),
                ("netbox_result", models.CharField(max_length=255)),
                (
                    "run_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="data.netboxorthoscomparisionrun",
                    ),
                ),
            ],
        ),
    ]
