# Generated by Django 4.2.23 on 2025-07-28 11:53

from django.db import migrations, models

import orthos2.data.validators


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0049_netboxorthoscomparisionrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmc",
            name="netbox_last_fetch_attempt",
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name="NetBox Last Fetched at",
            ),
        ),
        migrations.AddField(
            model_name="enclosure",
            name="netbox_last_fetch_attempt",
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name="NetBox Last Fetched at",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="netbox_last_fetch_attempt",
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name="NetBox Last Fetched at",
            ),
        ),
        migrations.AddField(
            model_name="networkinterface",
            name="netbox_last_fetch_attempt",
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name="NetBox Last Fetched at",
            ),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="location_rack",
            field=models.CharField(default="<not set>", max_length=512),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="location_rack_position",
            field=models.CharField(default="<not set>", max_length=512),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="location_room",
            field=models.CharField(default="<not set>", max_length=512),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="location_site",
            field=models.CharField(default="<not set>", max_length=512),
        ),
        # The garbage default value is fine as this migration should not work and an automated setting of the value
        # is impossible.
        migrations.AlterField(
            model_name="remotepowerdevice",
            name="mac",
            field=models.CharField(
                default="AA:BB:CC:DD:EE:FF",
                max_length=17,
                unique=True,
                validators=[orthos2.data.validators.validate_mac_address],
            ),
            preserve_default=False,
        ),
    ]
