# Generated by Django 4.2.23 on 2025-07-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0050_bmc_netbox_last_fetch_attempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enclosure",
            name="description",
            field=models.CharField(
                blank=True, help_text="Description of the Enclosure.", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="location_site",
            field=models.CharField(
                default="<not set>", help_text="The physical location.", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="name",
            field=models.CharField(
                help_text="The name given to the enclosure.",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                help_text="The Platform of the Enclosure",
                limit_choices_to={"is_cartridge": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.platform",
            ),
        ),
    ]
