# Generated by Django 4.2.30 on 2026-04-21 09:25

import django.db.models.deletion
from django.core.management import CommandError
from django.db import migrations, models


def set_architecture_and_domain(apps, schema_editor):
    RemotePowerDevice = apps.get_model("data", "RemotePowerDevice")
    Architecture = apps.get_model("data", "Architecture")
    Domain = apps.get_model("data", "Domain")

    try:
        embedded_arch = Architecture.objects.get(name="embedded")
    except Architecture.DoesNotExist:
        raise CommandError(
            '"embedded" architecture does not exist! Please create it first.'
        )

    for device in RemotePowerDevice.objects.all():
        device.architecture = embedded_arch
        device_fqdn = device.fqdn.split(".", 1)[1]
        try:
            device.domain = Domain.objects.get(name=device_fqdn)
        except Domain.DoesNotExist:
            raise CommandError(
                'Domain "%s" does not exist! Please create it first.' % device_fqdn
            )

        device.save()


def reverse_architecture_and_domain(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0051_alter_enclosure_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotepowerdevice",
            name="architecture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.architecture",
            ),
        ),
        migrations.AddField(
            model_name="remotepowerdevice",
            name="domain",
            field=models.ForeignKey(
                help_text="The domain name of the primary NIC",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.domain",
            ),
        ),
        migrations.RunPython(
            set_architecture_and_domain, reverse_code=reverse_architecture_and_domain
        ),
        migrations.AlterField(
            model_name="remotepowerdevice",
            name="architecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data.architecture",
            ),
        ),
        migrations.AlterField(
            model_name="remotepowerdevice",
            name="domain",
            field=models.ForeignKey(
                help_text="The domain name of the primary NIC",
                on_delete=django.db.models.deletion.CASCADE,
                to="data.domain",
            ),
        ),
        migrations.AddField(
            model_name="remotepowerdevice",
            name="ip_address_v4",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IPv4 address",
                null=True,
                protocol="IPv4",
                unique=True,
                verbose_name="IPv4 address",
            ),
        ),
        migrations.AddField(
            model_name="remotepowerdevice",
            name="ip_address_v6",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IPv6 address",
                null=True,
                protocol="IPv6",
                unique=True,
                verbose_name="IPv6 address",
            ),
        ),
        migrations.AddField(
            model_name="remotepowerdevice",
            name="netbox_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The ID that NetBox gives to the object.",
                verbose_name="NetBox ID",
            ),
        ),
        migrations.AddField(
            model_name="remotepowerdevice",
            name="netbox_last_fetch_attempt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="NetBox Last Fetched at"
            ),
        ),
        migrations.AddField(
            model_name="netboxorthoscomparisionrun",
            name="object_remote_power_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="netboxorthoscomparisionruns",
                to="data.remotepowerdevice",
            ),
        ),
        migrations.AlterField(
            model_name="netboxorthoscomparisionrun",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("bmc", "BMC"),
                    ("enclosure", "Enclosure"),
                    ("machine", "Machine"),
                    ("network_interface", "Network Interface"),
                    ("remote_power_device", "Remote Power Device"),
                ],
                max_length=50,
            ),
        ),
    ]
