# Generated by Django 4.2.30 on 2026-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0052_remotepowerdevice_architecture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="kernel_options_discovered",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Kernel command line parameters discovered from the running system (read-only)",
                max_length=4096,
                verbose_name="Kernel Options (Discovered)",
            ),
        ),
    ]
