# Generated by Django 4.2.x on 2026-04-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0053_machine_kernel_options_discovered"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PCIDevice",
        ),
    ]
