# Generated by Django 6.0.4 on 2026-04-28 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0054_remove_pcidevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsibleScanResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this scan was executed",
                    ),
                ),
                (
                    "facts_raw",
                    models.JSONField(
                        help_text="Complete ansible_facts dictionary as JSON"
                    ),
                ),
                (
                    "ansible_version",
                    models.CharField(
                        blank=True,
                        help_text="Ansible version used for this scan",
                        max_length=50,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine this scan belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ansible_scan_results",
                        to="data.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-run_date"],
                "indexes": [
                    models.Index(
                        fields=["machine", "-run_date"],
                        name="data_ansibl_machine_5a92dc_idx",
                    )
                ],
            },
        ),
    ]
