# Generated by Django 4.2.23 on 2026-05-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0055_ansiblescanresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="enclosure",
            name="is_virtual",
            field=models.BooleanField(
                default=False,
                help_text="Is the Enclosure a Virtual Machine or Device in NetBox?",
                verbose_name="Is Virtual?",
            ),
        ),
    ]
