# Generated by Django 4.2.23 on 2026-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0056_enclosure_is_virtual"),
    ]

    operations = [
        migrations.AddField(
            model_name="serialconsoletype",
            name="has_ipmi_sol",
            field=models.BooleanField(
                default=False,
                help_text="If the serial console type has IPMI SOL?",
                verbose_name="Has IPMI SOL?",
            ),
        ),
    ]
