# Generated by Django 4.2.23 on 2026-08-03 10:21

import re

from django.db import migrations

TAKEN_AWAY_BY_RE = re.compile(r"\s*\(taken away by [\w.@+-]+\)")


def scrub_reservationhistory_pii(apps, schema_editor):
    """Remove usernames from ReservationHistory before dropping reserved_by (GDPR)."""
    ReservationHistory = apps.get_model("data", "ReservationHistory")

    for history in ReservationHistory.objects.using(
        schema_editor.connection.alias
    ).all():
        scrubbed_reason = TAKEN_AWAY_BY_RE.sub("", history.reserved_reason).strip()

        history.reserved_by = ""
        history.reserved_reason = scrubbed_reason
        history.save(update_fields=["reserved_by", "reserved_reason"])


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0058_machine_reserved_permanently"),
    ]

    operations = [
        migrations.RunPython(scrub_reservationhistory_pii, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="reserved_by",
        ),
    ]
