# Generated by Django 4.2.11 on 2026-08-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0059_remove_reservationhistory_reserved_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinegroupmembership",
            name="group",
        ),
        migrations.RemoveField(
            model_name="machinegroupmembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="group",
        ),
        migrations.DeleteModel(
            name="MachineGroup",
        ),
        migrations.DeleteModel(
            name="MachineGroupMembership",
        ),
    ]
