# Generated by Django 4.2.11 on 2026-08-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0064_devicetype_netbox_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotepower",
            name="fence_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.remotepowertype",
                verbose_name="Fence Agent",
            ),
        ),
    ]
