# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 13:06
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=200)),
                ('arguments', models.TextField(default='[[], {}]')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'high'), (10, 'normal'),
                                                      (20, 'low')], default=10)),
                ('running', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now,
                                                     editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=200)),
                ('arguments', models.TextField(default='[[], {}]')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'high'), (10, 'normal'),
                                                      (20, 'low')], default=10)),
                ('running', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
