# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytask',
            options={'verbose_name': 'Daily Task'},
        ),
        migrations.AlterModelOptions(
            name='singletask',
            options={'verbose_name': 'Single Task'},
        ),
    ]
