# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20170830_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'high'), (10, 'normal')], default=10),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'high'), (10, 'normal')], default=10),
        ),
    ]
