services:
  authentik-postgresql:
    env_file:
      - docker/authentik/authentik.env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_USER: ${PG_USER:-authentik}
    networks:
      - orthos
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - database:/var/lib/postgresql/data

  authentik-server:
    command: server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    networks:
      - orthos
    env_file:
      - docker/authentik/authentik.env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.1}
    ports:
    - ${COMPOSE_PORT_HTTP:-9000}:9000
    - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - ./data:/data
    - ./custom-templates:/templates
    - ./traefik_certs:/certs
    - ./docker/authentik/blueprints:/blueprints/custom:ro,z
    security_opt:
      - label:disable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik-rtr.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr.tls=true"
      - "traefik.http.routers.authentik-rtr.rule=Host(`authentik.orthos2.test`)"
      - "traefik.http.routers.authentik-output-rtr.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.orthos2.test`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadbalancer.server.port=9000"

  authentik-worker:
    command: worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
      - docker/authentik/authentik.env
    networks:
      - orthos
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.1}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:z
    - ./data:/data
    - ./certs:/certs
    - ./custom-templates:/templates:ro,z
    - ./traefik_certs:/certs
    - ./docker/authentik/blueprints:/blueprints/custom:ro,z
    security_opt:
      - label:disable
