{
 "title": "Orthos 2 Host Overview",
 "description": "Shows a combined overview of Prometheus exporter data, over the Orthos 2 infrastructure",
 "tags": [
  "orthos2",
  "black_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Systems Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (probe_success == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Systems down",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (probe_success == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availibility over the last 24h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time((max by (instance) (probe_success))[24h:1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (job) (probe_success{job=~\"icmp-arch-ipv4|icmp-arch-ipv6\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances where icmp over IPv4 was unsuccessful",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{job=\"icmp-arch-ipv4\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances where icmp over IPv6 was unsuccessful",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{job=\"icmp-arch-ipv6\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}