{
 "title": "Orthos 2 Host Details",
 "description": "Shows the combined details of Prometheus exporter data, over a single Orthos 2 managed host",
 "tags": [
  "orthos2",
  "blackbox_exporter"
 ],
 "time": { "from": "now-4h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "icmp-arch-ipv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"$instance\", job=\"icmp-arch-ipv4\"}",
     "legendFormat": "IPv4 Ping success"
    }
   ]
  },
  {
   "title": "icmp-arch-ipv6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"$instance\", job=\"icmp-arch-ipv6\"}",
     "legendFormat": "IPv6 Ping success"
    }
   ]
  },
  {
   "title": "DNS Lookup IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"$instance\", job=\"icmp-arch-ipv4\"}",
     "legendFormat": "time in s"
    }
   ]
  },
  {
   "title": "DNS Lookup IPv6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"$instance\", job=\"icmp-arch-ipv6\"}",
     "legendFormat": "time in s"
    }
   ]
  },
  {
   "title": "Probe duration IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$instance\", job=\"icmp-arch-ipv4\"}",
     "legendFormat": "time in s"
    }
   ]
  },
  {
   "title": "Probe duration IPv6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$instance\", job=\"icmp-arch-ipv6\"}",
     "legendFormat": "time in s"
    }
   ]
  },
  {
   "title": "IPv4 RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=\"$instance\", job=\"icmp-arch-ipv4\", phase=\"rtt\"}",
     "legendFormat": "time in s"
    }
   ]
  },
  {
   "title": "Packet hop limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "probe_icmp_reply_hop_limit{instance=\"$instance\"}",
     "legendFormat": "hops"
    }
   ]
  }
 ]
}