name: Lint
on:
  push:
    branches:  [ master ]
  pull_request:
    branches: [ master ]

jobs:
  isort:
    name: isort
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.6
    - uses: isort/isort-action@master
      with:
        requirementsFiles: "pyproject.toml"
